### ISSUE TITLE
suggestion: explain what the tool does

### ISSUE THREAD

**Issue by jcollum-hcg** [scarygliders/X11RDP-o-Matic#35]
Been reading about this tool for a bit now (and in the middle of building it) and I honestly don't know whether this is intended to allow me to connect to a Debian machine via RDP-ish or if it's a tool that allows people to connect to my machine via RDP. In short: should this be installed on the machine I want to connect _to_ or the machine I want to connect _from_?

**Comment by metalefty** [comment]
closing.
