### ISSUE TITLE
Compilation with Multi-core CPU

### ISSUE THREAD

**Issue by Elvinra** [scarygliders/X11RDP-o-Matic#40]
I'm tried to perform a compilation of x11rdp and xrdp but when i saw my CPU in htop, just one core was used. I don't specify the flag --nocpuoptimize.

I already created a patch but i'm not able to push in a new branch for create a pull request :/

The patch is on a pastbin :
http://pastebin.com/LJrYrF1H

**Comment by nvtkaszpir** [comment]
I guess this can be closed, as stated in the documentation.
