### ISSUE TITLE
Dialog border lines show up wrong

### ISSUE THREAD

**Issue by ygoe** [scarygliders/X11RDP-o-Matic#45]
Instead of lines, I actually get the letters l, q, k, x, m and j everywhere. That looks weird. Other dialog-based package configurations work well. I'm using PuTTY to access the SSH shell. There are some options in PuTTY to handle strange output but none helps. So I guess these characters are somehow hard-coded in your script.

**Comment by shaunfreeman** [comment]
I came across this problem recently on my own project the dialog command needs the option '--ascii-lines' added to avoid this. Hope this helps. I know this is an old issue but your last comment was 'there was nothing you could do' but you could try this.

**Comment by shaunfreeman** [comment]
On more research at the top of the script addind

    export NCURSES_NO_UTF8_ACS=1

will solve this problem as this is an ncurses problem with UTF-8

**Comment by forigato** [comment]
Very good shaunfreeman ,
Tks!!!

**Comment by paramientos** [comment]
> On more research at the top of the script addind
> 
> ```
> export NCURSES_NO_UTF8_ACS=1
> ```
> 
> will solve this problem as this is an ncurses problem with UTF-8

Saved my day thx

**Comment by Evident-Dev** [comment]
I was able to fix this by going to the putty setting `Connection>Data` and changing the `Terminal-type string` from `xterm` to `linux`. 

![image](https://user-images.githubusercontent.com/9062825/112454652-26855000-8d16-11eb-90d2-86a3250d3d68.png)
