### ISSUE TITLE
xrdp 0.9+master build fail on Debian Jessie

### ISSUE THREAD

**Issue by ccwang002** [scarygliders/X11RDP-o-Matic#46]
I tried the devel branch of X11RDP-o-Matic with following command,

~~~bash
$ sudo ./X11rdp-o-matic.sh --branch master --withsimplesound --withpulse --justdoit
# ... skipped
----------------------------------------------------------------------
Preparation complete. Building and packaging xrdp...
----------------------------------------------------------------------
# ... skipped
dh binary
   dh_testroot
   dh_prep
   dh_auto_install
   dh_installdocs
cp: cannot stat ‘NEWS’: No such file or directory
dh_installdocs: cp -a NEWS debian/xrdp/usr/share/doc/xrdp returned exit code 1
debian/rules:22: recipe for target 'binary' failed
make: *** [binary] Error 2
~~~

It seems that without `NEWS` file the xrdp package build process fails, therefore no `xrdp*.deb` will be produced. How should I create such `NEWS` file?

Also I found the thread neutrinolabs/xrdp#190 about Debian Jessie systemd script not being produced. Will this be another potential failure?

**Comment by DimitryAndric** [comment]
I think this diff should fix it:
```diff
diff --git a/xrdp_docs b/xrdp_docs
index 2f6f119..4eea462 100644
--- a/xrdp_docs
+++ b/xrdp_docs
@@ -1,5 +1,4 @@
 design.txt
 faq-general.txt
-NEWS
 prog_std.txt
 readme.txt
```

**Comment by metalefty** [comment]
I've pushed the fix to devel branch. 
@ccwang002, can you test it?

**Comment by ccwang002** [comment]
I don't have a Jessie machine with me right now. Can test it next week. If anyone can help, feel free to take over.

**Comment by metalefty** [comment]
I confirmed the build on Jessie in #61.
