### ISSUE TITLE
platform Ubuntu Server 14.04

### ISSUE THREAD

**Issue by azat-aimfund** [scarygliders/X11RDP-o-Matic#48]
this is not an issue
just wanted to say, that script 
./X11rdp-o-matic.sh –justdoit
works fine on Ubuntu 14.04.2 Server

**Comment by hapylestat** [comment]
working fine on Ubuntu 15.05, but with some exceptions.
1) Need to use xfce de to be able to login. For that, apt-get install xfce4
2) echo xfce4-session >~/.xsession

additionally xrdp and xrdp-sessman will not start out of box via systemd =\ But working fine with -ns params

**Comment by m42e** [comment]
can you explain about which -ns switch you are talking about? @hapylestat

**Comment by jsorg71** [comment]
the -ns switch stands for "no service" or "no daemon"
It means run in foreground and not daemonize.

**Comment by hapylestat** [comment]
@jsorg71 correct, systemd do the job for making process to be daemon, otherwise he think that process die (not really known how daemonization is realized on xrdp).
