### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by vozzibaer** [scarygliders/X11RDP-o-Matic#51]
Hi,

on my Kubuntu 14.04 desktop while building X11rdp I have an error:

"failed to download libXfont-1.4.3.tar.bz - aborting build"

Any suggestions here?

**Comment by scarygliders** [comment]
This is more likely to be a problem with the x11rdp script called "buildx.sh) which o-Matic makes use of (as o-Matic doesn't do the actual downloading and compiling of x11rdp itself - it merely downloads the x11rdp source and runs the buildx.sh script).

It might just be a temporary glitch in how buildx.sh downloads the source files it needs.

I say wait for a while then try running o-Matic again. If it still doesn't work, then try filing an Issue at https://github.com/neutrinolabs/xrdp

**Comment by vozzibaer** [comment]
Hm, I try downloading this file with wget - no problem. But the buildx.sh script is stopping at the same file (libXfont-1.4.3.tar.bz). Any ideas?

**Comment by metalefty** [comment]
It's out of scope now.
