### ISSUE TITLE
Drive redirection does not work

### ISSUE THREAD

**Issue by lorenzoverbicaro** [scarygliders/X11RDP-o-Matic#57]
I can´t redirect drives, even using the ./configure --enable-fuse command. I've tried all the branchs of neutrinolabs/xrdp, and installing in various Debian and Ubuntu distros. The clipboard files works perfectly in both ways, but the drive redirection looks simply does not exist, despite the thinclient_drive folder always appear. What can I be missing?

**Comment by metalefty** [comment]
Duplicate of neutrinolabs/xrdp#308.
