### ISSUE TITLE
Crashes on Ubuntu 15.10

### ISSUE THREAD

**Issue by romu70** [scarygliders/X11RDP-o-Matic#58]
Hi,
X11RDP crashes a lot on Ubuntu 15.10. Don't know if this is the right place to raise such a bug, so feel free to advice.

Thanks.

**Comment by scarygliders** [comment]
I think you should be reporting that here instead : https://github.com/neutrinolabs/xrdp/issues

Regards

**Comment by metalefty** [comment]
closing.
