### ISSUE TITLE
Switch the keyboard does not work in a terminal session

### ISSUE THREAD

**Issue by mkukushkin35** [scarygliders/X11RDP-o-Matic#62]
Keyboard switch starts only after I run the command in the session:
`setxkbmap -layout "us,ru" -model "pc105" -option "grp:alt_shift_toggle,grp_led:scroll"`
And it did not work and when resuming session.
What should be done or where I can add this command that would switch worked immediately when entering a session?

**Comment by scarygliders** [comment]
This is the wrong place for your issue - it should go here : https://github.com/neutrinolabs/xrdp/issues

Regards
