### ISSUE TITLE
rootless build

### ISSUE THREAD

**Issue by metalefty** [scarygliders/X11RDP-o-Matic#63]
Require root privilege only really needed.

**Comment by fang64** [comment]
@metalefty I'm not sure this is what the same, but it seems some of the folks who work on the Arctica Project have updated the upstream debian package build routine in a git repository 
https://anonscm.debian.org/git/collab-maint/xrdp.git

I do know this is the sid release of debian but,
https://packages.debian.org/source/sid/xrdp

These guys have a build environment that is sane it appears.

**Comment by metalefty** [comment]
Thank you for information.  Yes, xrdp can be built without root privilege. It is very easy to build xrdp without root. This is why xrdp is packaged.

But building x11rdp requires root privilege or write access to `/opt` directory.  My thought of this issue is to build xrdp without root and build x11rdp with root.  The goal of this issue is to gain root privileges on demand via sudo like X11RDP-RH-Matic.

I also thinking to obsolete x11rdp support and switch to xorgxrdp (xorg driver) instead x11rdp.

**Comment by metalefty** [comment]
done in #76
