### ISSUE TITLE
remove interactive mode

### ISSUE THREAD

**Issue by metalefty** [scarygliders/X11RDP-o-Matic#64]
o-Matic has two modes interactive and non-interactive.

Current o-Matic code is not doing DRY and contains repeat of similar operations.
I think most of people use o-Matic with `--justdoit` option.  I would like to remove 
interactive mode rather than refactor keeping two modes.

Any opinions?

**Comment by scarygliders** [comment]
I don't have any objections to that. Really, the interactive mode was mostly me learning how to make an interactive bash script with menus - had a lot of fun learning that way back when ;)

But seriously - removing it would be Keeping It Simple, and I like the KISS principle these days.

Although alternatively I can see a way in which the script could be rewritten with interactive mode in mind but just reuses the functions used by --justdoit.

I'd do that myself but really these days I've honestly lost interest in the whole xrdp thing and have moved on. :)

Regards.

**Comment by metalefty** [comment]
No problem, I still have interest in xrdp.  

Some people complained that o-Matic doesn't work on Ubuntu 16.04 since people also still want to use useful your tool. Someone have to maintain o-Matic for that reason.  I do as I can.

However, I also doing my own RH-Matic for Red Hat clones. To maintain both of these in finite time, o-Matic can be simplified and needs to be simplified. This is anther reason to remove interactive mode.

Simplifying not necessarily means removing interactive mode.  After simplifying o-Matic, I'm going to do xorgxrdp build and rootless build. Thanks for your work so far.
