### ISSUE TITLE
Error compiling on raspberry pi 2 ubuntu mate 16.04

### ISSUE THREAD

**Issue by BuTbka86** [scarygliders/X11RDP-o-Matic#66]
I am try master and devel branches

./X11rdp-o-matic.sh --branch master
...
...
...

checking for DRI... no  
configure: error: Package requirements (glproto >= 1.4.10 dri >= 7.8.0)  
Package 'dri' requires 'libdrm >= 2.4.60' but version of libdrm is 2.4.26

pkg-config --modversion libdrm
2.4.68

**Comment by ricadelic** [comment]
You can replace libdrm 2.4.26 with libdrm 2.4.60 and use the build-switch  --disable-cairo-tests in x11_file_list.txt.

**Comment by metalefty** [comment]
neutrinolabs/xrdp is appropriate place to report the issue. I'll do it.
