### ISSUE TITLE
mate-ubuntu 16.04.1

### ISSUE THREAD

**Issue by coolemza** [scarygliders/X11RDP-o-Matic#70]
mate-ubuntu 16.04.1, fresh install:
sudo ./X11rdp-o-matic.sh --branch devel --justdoit
...
Email-Address       : root@unknown
License             : apache
Package Name        : xrdp
Maintainer Name     : root
Version             : 0.9.0+devel
Package Type        : single
Date                : Mon, 15 Aug 2016 19:25:23 +0300
Done. Please edit the files in the debian/ subdirectory now.
---
## Preparation complete. Building and packaging xrdp...

dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: error: gain-root-commmand 'fakeroot' not found

**Comment by hutm** [comment]
`apt install fakeroot` solves the problem

**Comment by metalefty** [comment]
Fixed in devel branch.
