### ISSUE TITLE
X11RDP build

### ISSUE THREAD

**Issue by CMCDragonkai** [scarygliders/X11RDP-o-Matic#71]
I'm interested in packing this for NixPkgs, just wondering is your x11rdp build the same as: http://scarygliders.net/2011/09/23/install-xrdp-and-x11rdp-the-comprehensive-howto-for-ubuntu-and-debian-based-systems/

Otherwise, where did you get the new x11rdp? A quick `CTRL + F` didn't show the same URL for x11rdp.

**Comment by metalefty** [comment]
x11rdp is a part of xrdp. you can find it in xrdp's source tree.
https://github.com/neutrinolabs/xrdp/tree/devel/xorg/X11R7.6
