### ISSUE TITLE
install fails dpkg-buildpackage

### ISSUE THREAD

**Issue by EnzephaloN** [scarygliders/X11RDP-o-Matic#79]
Hello
I've tried to install on Debian 8.5. 
At "building xrdp source and oackaging..." I get many errors:
`dpkg-source: error: add xorg/X11R7.6/build_dir/xorg-server-1.9.3/os/.libs/

dpkg-source: error: cannot represent change to xorg/X11R7.6&build_dir/xorg

...

dpkg-source: error: unrepresentable changes to source

dpkg-buildpackage: error: dpkg-source -b xdrp-0.9.0+master gave error exit

mv : cannot stat 'xrdp*.deb': No such file or directory`

What can I do?

**Comment by metalefty** [comment]
devel branch of X11RDP-o-Matic is the branch currently supported.  However, upstream is significantly changed day by day in recent a few weeks. This tool doesn't fully chase upstream changes.

**Comment by EnzephaloN** [comment]
Hello
I used this http://www.cb-net.co.uk/linux/getting-x11rdp-working-on-debian-8-jessie-with-the-help-of-x11rdp-o-matic/ tutorial, after some fixes it worked. But, only one time. I can connect, but the connection closes immedently because of wrong state of listener. But this is another problem.
