### ISSUE TITLE
decrease time of kill Disconnected sessions

### ISSUE THREAD

**Issue by purvalpatel** [scarygliders/X11RDP-o-Matic#86]
how to decrease time of kill disconnected sessions to 60 seconds?

**Comment by metalefty** [comment]
Set `DisconnectedTimeLimit` less than 60 (not zero).

**Comment by metalefty** [comment]
Ah, you should create the issue at [neutrinolabs/xrdp](https://github.com/neutrinolabs/xrdp).
Here's not the place.
