### ISSUE TITLE
The script crash with --justdoit without messages

### ISSUE THREAD

**Issue by Body4** [scarygliders/X11RDP-o-Matic#87]
Hello,
I noticed that your script return an error code 8 of wget at the line 679 of X11RDP-o-Matic.sh which cause the crash without any errors messages.

The line `README="https://raw.github.com/neutrinolabs/xrdp/$XRDPBRANCH/readme.txt"` must be replaced by `README="https://raw.github.com/neutrinolabs/xrdp/$XRDPBRANCH/README.md"`. 

The file readme.txt was replaced by README.md on the repository "xrdp" of neutrinolabs.

Body

**Comment by metalefty** [comment]
Please read #84.
