### ISSUE TITLE
Trying on ubuntu14

### ISSUE THREAD

**Issue by ps2k** [scarygliders/X11RDP-o-Matic#88]
I was able to get this working perfectly 2.5 years back on my ubuntu 14.04. I'm now trying to setup on new ubuntu 14.04, things don't work. running "X11rdp-o-matic.sh --justdoit" doesn't do anything. It simply exits after couple of seconds. Then tried branches v2.5. This was good. However only LDM and KDM worked. Even xfce didn't work (later I found that didn't get installed at all). I was able to retain my open sessions and workspace when I disconnected and reconnected back. I was happy. However after reboot this feature didn't work at all. I was pretty disappointed. I went to this solution 2.5 yrs back was no other RDP solution worked for me. Then I tried v3.3, even that has the same issues. Looks like something is broken. 
I would really appreciate if somebody help me with it.

**Comment by metalefty** [comment]
Please read #84.
